# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 18:43
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170407_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.get_image_filename, verbose_name='Image')),
                ('article', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Article')),
            ],
        ),
        migrations.RemoveField(
            model_name='articleimage',
            name='article',
        ),
        migrations.DeleteModel(
            name='ArticleImage',
        ),
    ]
